# **************************************************************************
# *
# * Authors:     David Herreros Calero (dherreros@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************


from pyworkflow import NEW
from pyworkflow.protocol.params import PointerParam
from pyworkflow.object import Boolean

from pwem.protocols import ProtAnalysis3D, ProtFlexBase


class ProtFlexAssociateSpace(ProtAnalysis3D, ProtFlexBase):
    """ Associate flexible spaces and info to a different set of particles """

    """
        Associate Flexible Space to Particles (ProtFlexAssociateSpace) — User Manual

            Overview

            The ProtFlexAssociateSpace protocol transfers flexibility-related information from a
            reference set of flexible particles to another particle dataset. Its main purpose is
            to preserve conformational descriptors, latent-space coordinates, and associated
            flexibility metadata while updating the particle locations to match a different
            particle set. This allows biological interpretation and downstream analysis of
            alternative particle datasets using previously computed flexibility information.

            Inputs and General Workflow

            The protocol requires two particle sets. The first input contains particles with
            previously computed flexibility information, such as latent coordinates or
            conformational descriptors generated by methods like Zernike3D or CryoDRGN.
            The second input corresponds to the target particle dataset that will receive this
            information.

            During execution, the protocol creates a new flexible particle set by copying the
            flexibility metadata from the reference particles and associating it with the
            spatial locations of the target particles. Each particle from both datasets is
            matched sequentially, ensuring that flexibility information remains consistent
            across the new output dataset.

            Outputs and Interpretation

            After execution, the protocol produces a new SetOfParticlesFlex object containing
            the target particles enriched with the transferred flexibility information. The
            resulting dataset preserves the original conformational descriptors while adapting
            them to the new particle locations.

            Biological Perspective

            This protocol is especially useful in cryo-EM workflows where flexibility analysis
            has already been computed on one particle dataset and needs to be reused on another
            aligned, filtered, or reprocessed dataset. By preserving the conformational space,
            users can continue biological interpretation without recomputing the flexibility
            analysis from the beginning.

            Final Perspective

            ProtFlexAssociateSpace provides a simple and efficient mechanism for reusing
            previously computed conformational information across different particle datasets.
            This facilitates flexible-region analysis, comparative studies, and downstream
            structural interpretation in cryo-EM workflows.
        """
    _label = 'associate flex space to particles'
    _devStatus = NEW
    OUTPUT_PREFIX = 'flexParticles'

    # --------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        form.addSection(label='General parameters')
        form.addParam('particlesFlex', PointerParam, label="Particles with flex info",
                      pointerClass='SetOfParticlesFlex', important=True,
                      help="Particles must have a flexibility information associated (Zernike3D, CryoDrgn...")
        form.addParam('particles', PointerParam, label="Particles to associate",
                      pointerClass="SetOfParticles", important=True,
                      help='Particles to associate flexibility information (space and other attributes)')

    # --------------------------- INSERT steps functions ----------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self._createOutputStep)

    # --------------------------- STEPS functions -----------------------------
    def _createOutputStep(self):
        particlesFlex = self.particlesFlex.get()
        particles = self.particles.get()

        outSet = self._createSetOfParticlesFlex()
        outSet.copyInfo(particlesFlex)
        outSet.setHasCTF(particlesFlex.hasCTF())

        for particleFlex, particle in zip(particlesFlex.iterItems(), particles.iterItems()):
            particleFlex.setLocation(particle.getLocation())
            outSet.append(particleFlex)

        # Save new output
        name = self.OUTPUT_PREFIX
        args = {}
        args[name] = outSet
        self._defineOutputs(**args)
        self._defineSourceRelation(particlesFlex, outSet)
        self._defineSourceRelation(particles, outSet)

    # --------------------------- INFO functions -----------------------------
    def _summary(self):
        summary = []
        if self.getOutputsSize() >= 1:
            summary.append("Particles successfully associated")
        else:
            summary.append("Output annotated classes not ready yet")
        return summary

    def _methods(self):
        return [
            "Associate flexiblity information to a different set of particles",
        ]

    # ----------------------- VALIDATE functions ----------------------------------------
    def validate(self):
        """ Try to find errors on define params. """
        errors = []
        return errors
